### PR TITLE
Adding a new status feature

### PR DESCRIPTION
**Pull request by rajinipa**
Dear rajini,
    you are doing is great service, I have added a new status feature called status.kindly request and merge this your code

### CODE REVIEW

**Comment by rajinipa** [comment]
Dear rajini tqs and keep supporting

**Comment by rajinipa** [comment]
Kindly review and merge this code.Include the Audio and video code

**Comment by rajparama** [comment]
Dear LAO,thanks for adding your code. keep supporting

**Comment by rajiniparamasivam** [comment]
Dear LAO, thanks for your code.keep supporting

**Pull request merged**
